### ISSUE TITLE
CPU config

### ISSUE THREAD

**Issue by alzeha** [ricpacca/deaddrop#1]
Hi,
I am starting two terminals at my arch linux.

At the first, I give 
taskset -c 1 ./sender

At the second, I give
taskset -c 3 ./receiver

(using -c 5 as recommended in the pdf is returning invalid argument).

After that I am pressing enter to begin listening, but if I type a message at the sender terminal, nothing happens at the receiver side. Can you explain why?

I am using a Intel Core I7 6770K and I already deactivated Hyper Threading, Virtualization, Hardware Prefetching and Cache Line Prefetching, but nothing helped :(

Thanks in advance

**Comment by ricpacca** [comment]
Hi alzeha, have you set the page size to 2 MB (huge pages enabled)?

**Comment by alzeha** [comment]
Hi,

thanks for your reply!

I am using huge pages now. Still nothing is happening.

At the first terminal, I give:
LD_PRELOAD=libhugetlbfs.so HUGETLB_MORECORE=yes taskset -c 1 ./sender

At the second terminal, I give:
LD_PRELOAD=libhugetlbfs.so HUGETLB_MORECORE=yes taskset -c 1 ./receiver

Pressing enter to begin listening, typing a message, receiver does still not receive.

While running the two processes, I was opening a third terminal:
[alzeha@myArch ~]$ cat /proc/meminfo
MemTotal:       65902420 kB
MemFree:        62206008 kB
MemAvailable:   62411316 kB
Buffers:           62156 kB
Cached:           894316 kB
SwapCached:            0 kB
Active:          1835728 kB
Inactive:         464520 kB
Active(anon):    1345224 kB
Inactive(anon):    96748 kB
Active(file):     490504 kB
Inactive(file):   367772 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        511996 kB
SwapFree:         511996 kB
Dirty:              5344 kB
Writeback:             0 kB
AnonPages:       1343852 kB
Mapped:           381808 kB
Shmem:             98200 kB
Slab:             117388 kB
SReclaimable:      68888 kB
SUnreclaim:        48500 kB
KernelStack:        9200 kB
PageTables:        18952 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    32938916 kB
Committed_AS:    4591988 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             1280 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
**HugePages_Total:     512
HugePages_Free:      506**
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         1048576 kB
DirectMap4k:      145384 kB
DirectMap2M:     8175616 kB
DirectMap1G:    58720256 kB

Please recognize, that HugePages_Total is more than HugePages_Free.

After killing the two processes:
[alzeha@myArch ~]$ cat /proc/meminfo
MemTotal:       65902420 kB
MemFree:        62164544 kB
MemAvailable:   62369868 kB
Buffers:           62172 kB
Cached:           894200 kB
SwapCached:            0 kB
Active:          1869772 kB
Inactive:         464404 kB
Active(anon):    1379252 kB
Inactive(anon):    96632 kB
Active(file):     490520 kB
Inactive(file):   367772 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        511996 kB
SwapFree:         511996 kB
Dirty:              4744 kB
Writeback:             0 kB
AnonPages:       1377928 kB
Mapped:           381600 kB
Shmem:             98084 kB
Slab:             117376 kB
SReclaimable:      68888 kB
SUnreclaim:        48488 kB
KernelStack:        9104 kB
PageTables:        18888 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    32938916 kB
Committed_AS:    4591988 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             1280 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
**HugePages_Total:     512
HugePages_Free:      512**
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         1048576 kB
DirectMap4k:      145384 kB
DirectMap2M:     8175616 kB
DirectMap1G:    58720256 kB

Please recognize, that now HugePages_Total == HugePages_Free. So the two processes were using the huge pages.

Do you have any different ideas?

Thank you :)

**Comment by alzeha** [comment]
Maybe a different solution would be to make your VM somehow downloadable and show the link?

**Comment by ricpacca** [comment]
Have you tried to run the sender and the receiver without using `taskset`, meaning that the command would simply be `./sender` and `./receiver`?

**Comment by alzeha** [comment]
Huh, that's funny. Do you have an explanation, why it is working now?

**Comment by ricpacca** [comment]
That's great news! I suppose the reason why it did not work with `taskset -c 1` (meaning that both processes run on core 1) is that the timing to evict the `receiver`'s set from its L1 is much faster (in cycles) when the two processes run on the same core, and the actual timings used in the code were measured with `sender` and `receiver` running on different cores. Perhaps with some manual tuning you could get them to work with while running on the same core too!
