### ISSUE TITLE
Prime+Probe covert channel on sandybridge

### ISSUE THREAD

**Issue by JaspinderKaur07** [ricpacca/deaddrop#2]
Hey as cache slice hash function is mentioned for few processors such as sandybridge, haswell etc. did you try that?

**Comment by ricpacca** [comment]
Hello. I did not try that because I was testing my code on a CPU for which the slice mapping function was not publicly available.

**Comment by JaspinderKaur07** [comment]
Hi,
Thank you for your repky. I am also coming across the same problem. May I
please know which cpu you were trying for?
Any other solution you can suggest?

**Comment by JaspinderKaur07** [comment]
Another doubt: Links you have given claim to implement prime and probe
covert channel attack.

**Comment by ricpacca** [comment]
Yes, that was confusing but we fixed the README so that it explains how the covert channel actually works (with flush+reload). Also, because it's actually flush+reload the slice mapping function does not matter.
